language: ruby
cache:
  bundler: true
  directories:
    - node_modules
    - elm-stuff
rvm: 2.2.3
sudo: false
before_script:
  - npm install elm@0.16.0
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile

